# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
markdown:            redcarpet
pygments:            true

permalink:           pretty
relative_permalinks: true

# Setup
title:               Gaurav Dhanuka
description:         'Thinker // Designer // Developer'
baseurl:             '/'
paginate:            5

# About/contact
author:
  name:              Gaurav Dhanuka
  url:               https://twitter.com/prodroid_gaurav
  email:             gauravdhanuka2007@gmail.com

# Custom vars
version:          1.0.0
github:
  repo:               https://github.com/GauravDhanuka
