# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty


# Setup
title:               Gaurav Dhanuka
description:         'Thinker // Designer // Developer'
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Gaurav Dhanuka
  url:               https://twitter.com/prodroid_gaurav
  email:             gauravdhanuka2007@gmail.com
  image: 			 public/gaurav.jpg

# Custom vars
version:          1.0.0
github:
  repo:               https://github.com/GauravDhanuka
