# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Gaurav Dhanuka
tagline:             'Aka: proDroid'
description:         'Thinker // Designer // Developer'
url:                 http://lanyon.getpoole.com
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Gaurav Dhanuka
  url:               https://twitter.com/prodroid_gaurav
  email:             gauravdhanuka2007@gmail.com

# Custom vars
version:             1.0.0
